openapi: 3.1.0
info:
  title: Authorization Service API
  description: API of Authorization Service for interacting with your account
  version: 1.0.0
paths:
  /register:
    post:
      summary: Create a new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        '201':
          description: Account successfully created
        '400':
          description: Invalid name or password
        '409':
          description: User with this name already exists
        '500':
          description: Server error
  /login:
    post:
      summary: Logging into account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_token'
        '400':
          description: Invalid name or password
        '401':
          description: Incorrect password for this name
        '500':
          description: Server error
components:
  schemas:
    user:
      type: object
      description: User's account info
      properties:
        name:
          type: string
          description: User's name
        password:
          type: string
          description: User's password
      required:
        - name
        - password
    auth_token:
      type: string
      description: Authorization token
