version: "3.9"

services:
  user_database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data/

  routing_database:
    image: "postgres"
    env_file:
      - routing_database.env
    ports:
      - "5434:5432"
    volumes:
      - routing-data:/var/lib/postgresql/routing_data/

  photos:
    build:
      context: .
      dockerfile: photos/photos.Dockerfile
    ports:
      - "8083:8083"
    expose:
      - "8083"
    volumes:
      - pictures-data:/data/photos/

  auth:
    build:
      context: .
      dockerfile: auth/auth.Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - user_database

  routing:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - routing_database

  jams:
    image: "vovapolu/jams:0.1.0"
    ports:
      - "8080:8080"
    expose:
      - "8080"

volumes:
  user-data:
  routing-data:
  pictures-data:
