FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_2.13.10 AS build
WORKDIR /auth
COPY /auth /auth
ENV SBT_OPTS="-Xms4G -Xmx4G -Xss8M"
RUN sbt clean
RUN sbt assembly

FROM eclipse-temurin:19-jre-focal
RUN mkdir -p  /opt/auth-app
COPY --from=build /auth/target/scala-2.13/auth.jar /opt/auth-app/auth.jar
ENTRYPOINT ["java", "-jar", "/opt/auth-app/auth.jar"]
