FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_2.13.10 AS build
WORKDIR /routing
COPY /routing /routing
ENV SBT_OPTS="-Xms4G -Xmx4G -Xss8M"
RUN sbt clean
RUN sbt assembly

FROM eclipse-temurin:19-jre-focal
RUN mkdir -p  /opt/routing-app
COPY --from=build /routing/target/scala-2.13/routing.jar /opt/routing-app/routing.jar
ENTRYPOINT ["java", "-jar", "/opt/routing-app/routing.jar"]
