version: '3'

services:
  auth:
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint: ["java", "-jar", "/opt/app/auth.jar"]

  routing:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    entrypoint: ["java", "-jar", "/opt/app/routing.jar"]
