FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_2.13.10 AS build
WORKDIR /root
COPY . .
EXPOSE 8082
RUN sbt "auth / clean"
RUN sbt "auth / assembly"

FROM eclipse-temurin:19-jre-focal
RUN mkdir -p  /opt/app
COPY --from=build /root/auth/target/auth.jar /opt/app/auth.jar
ENTRYPOINT ["java", "-jar", "/opt/app/auth.jar"]
