version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  routing_database:
    image: "postgres"
    env_file:
      - routing_database.env
    ports:
      - "5434:5432"
    volumes:
      - database-data:/var/lib/postgresql/routing_data/

  auth:
    build:
      context: .
      dockerfile: auth/auth.Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - database

  routing:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"

volumes:
  database-data:
