version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: auth/auth.Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
  routing:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    entrypoint: bash -c "source ~/.sdkman/bin/sdkman-init.sh && sbt 'runMain routing.RoutingMain'"
