version: "3.9"

services:
  user_database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data/

  routing_database:
    image: "postgres"
    env_file:
      - routing_database.env
    ports:
      - "5434:5432"
    volumes:
      - routing-data:/var/lib/postgresql/routing_data/

  photos:
    build:
      context: .
      dockerfile: photos/photos.Dockerfile
    ports:
      - "8083:8083"
    expose:
      - "8083"
    volumes:
      - pictures-data:/data/photos/

  auth:
    build:
      context: .
      dockerfile: auth/auth.Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - user_database

  routing-balancer:
    image: nginx
    ports:
      - "8081:8081"
    volumes:
      - "./routing/balancer/nginx.conf:/etc/nginx/nginx.conf"

  routing-1:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8084:8084"
    expose:
      - "8084"
    depends_on:
      - routing_database

  routing-2:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8085:8085"
    expose:
      - "8085"
    depends_on:
      - routing_database

  routing-3:
    build:
      context: .
      dockerfile: routing/routing.Dockerfile
    ports:
      - "8086:8086"
    expose:
      - "8086"
    depends_on:
      - routing_database

volumes:
  user-data:
  routing-data:
  pictures-data:
