FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_2.13.10 AS build
WORKDIR /root
COPY . .
EXPOSE 8081
RUN sbt "routing / clean"
RUN sbt "routing / assembly"

FROM eclipse-temurin:19-jre-focal
RUN mkdir -p  /opt/app
COPY --from=build /root/routing/target/routing.jar /opt/app/routing.jar
ENTRYPOINT ["java", "-jar", "/opt/app/routing.jar"]
