name: test-build

on:
  push:
    branches:
      - main
      - task7
      # Эти ветки указаны в задании, но у нас таких нет
      - master
      - 'release/AdzhimaNikita/**'

jobs:
  buildx:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "build"
      - name: Cache SBT-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Test and format
        run: |
          sbt scalafmtCheckAll
          sbt test